# Generated by Django 5.1.1 on 2024-11-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filmes_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
    ]
