# Generated by Django 5.1.1 on 2024-11-01 11:42

from django.db import migrations

def inserir_genero_inicial(apps, schema_editor):
    Genero = apps.get_model('filmes_app', 'Genero')
    Genero.objects.create(descricao="Romance")

class Migration(migrations.Migration):
    dependencies = [
        ("filmes_app", "0002_genero"),
    ]

    operations = [
        migrations.RunPython(inserir_genero_inicial)
    ]
