# Generated by Django 5.1.1 on 2024-11-01 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filmes_app", "0003_inserir_genero_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="genero",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="filmes_app.genero",
            ),
            preserve_default=False,
        ),
    ]
